name: Feature Tamplate
description: 기능 추가할 때 쓰는 템플릿
title: "[Feature]: Feature Title"
labels: ["feature"]

body:
  - type: textarea
    id: feature-contents
    attributes:
      label: Feature 설명
      description: 작업할 Feature에 대한 설명을 적어주세요.
      placeholder: ex. json 파일 적용
    validations:
      required: true
  - type: textarea
    id: related-view
    attributes:
      label: Related View(Optional)
      description: 작업하는 사항에 영향을 받는 View(화면)
      value: |
        - ex. HomeView
    validations:
      required: false
      
  - type: dropdown
    id: priority
    attributes:
      label: 우선순위
      description: Backlog에서의 중요도
      options:
        - ★★★★★
        - ★★★★
        - ★★★
        - ★★
        - ★
    validations:
      required: true
      
  - type: input
    id: expected-period
    attributes:
      label: 예상 작업 기간
      placeholder: ~ MM/DD(E) ex. ~ 07/12(화)
    validations:
      required: true
  - type: input
    id: real-period
    attributes:
      label: 실제 작업 기간(Close 시점에 수정)
      placeholder: ~ MM/DD(E) ex. ~ 07/12(화)
    validations:
      required: false
